services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=bricol
      - POSTGRES_PASSWORD=bricol
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    image: bricol-server:latest
    user: root
    tty: true
    environment:
      - HOST=db
      - USER=bricol
      - PASSWORD=bricol
    ports:
      - "8088:8088"
    restart: always

volumes:
  pgdata:
